
name: opam-build-and-test
on: [push, pull_request]
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.11.0
          - 4.10.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - name: Install system dependencies
        run: opam depext modular-lang-proto.dev --yes --with-doc --with-test
      - name: Install dependencies
        run: opam install modular-lang-proto --deps-only
      - name: Build
        run: opam exec -- dune build
      - name: Run tests
        run: opam exec -- dune test
