
name: opam-build-and-test
on: [push, pull_request]
jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        ocaml-version:
          - 4.11.0
          - 4.10.1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: avsm/setup-ocaml@v1
        with:
          ocaml-version: ${{ matrix.ocaml-version }}
      - run: opam --version
      - run: opam install . --deps-only
      - run: opam exec -- ocamlopt --version
      - run: opam exec -- dune --version
      - run: opam exec -- dune build
      - run: opam exec -- dune test
